Taking INPUTS

In [ ]:
n=int(input())
l=[]
for i in range(n):
    l.append(int(input()))
    
#input of form

#n
#1
#2
#3
#4

In [ ]:
a=input().split()
n=int(a[0])
l=[int(i) for i in a[1:]]

#======= OR ========

a=input().split()
n=int(a[0])
l=[]
for i in a[1:]:
    l.append(int(i))

#input of form

#n 1 2 3 4

In [ ]:
n=int(input())
l=[int(i) for i in input().split()]
#input of form

#n
#1 2 3 4

Try and Except Python

In [1]:
def fun():
    try:
        print("try block")
    except :
        print ("except block")
    else:
        print ("else block")
  
fun()

try block
else block


In [2]:
def fun(a):
    try :
        print(a/0)
    except :
        print ("except block")
    else:
        print ("else block")
  
fun(1)

except block


In [3]:
def fun(a):
    try :
        print(a/0)
    except :
        print ("except block")
    else:
        print ("else block")
    finally:
        print("This is always run whether try block runs or except block")
  
fun(1)

except block
This is always run whether try block runs or except block


Args and Kwargs : Watch Coding Ninjas DSA playlist or GEEKFORGEEKS

In [5]:
pass

Unpacking of element into multiple arguments

In [4]:
def fun(*params):
    for i in params:
        print(i)

l=[1,2,3,4]
fun(*l)

1
2
3
4


HANDY IF ELSE USE

In [5]:
a=3
b=2
max=a if a>b else b
print("OUTPUT IS : ",max)

OUTPUT IS :  3


Pair sum CODESTUDIO 

In [6]:
from collections import *
def pairSum(arr, s):
    n=len(arr)

    map=OrderedDict()

    ans=[]

    for num in arr:
        map[num]=map.get(num,0)+1    # map[num] is freq of num  eg. if map is [(3,2),(1,1)] then map[3] gives 2
    
    KeyArr=sorted(map.keys())  #unique array element list

    for key in KeyArr:
        if key+key == s:
            freq=map[key]

            for j in range(freq*(freq-1)//2):  # freq=??????? combinations of 2 things out of freq things
                ans.append([key,key])
    
    low=0
    high=len(KeyArr)-1  # NOT high=n-1

    while(low<high):
        currsum=KeyArr[low]+KeyArr[high]
        if currsum==s:
            freq= map[KeyArr[low]]*map[KeyArr[high]]
            for j in range(freq):
                ans.append([KeyArr[low],KeyArr[high]])
            low+=1
            high-=1
        elif currsum>s:
            high-=1
        else:
            low+=1
    
    # Sorted result in end
    for i in range(len(ans)):
        a=ans[i][0]
        b=ans[i][1]
        ans[i][0]=min(a,b)
        ans[i][1]=max(a,b)
    
    
    ans=sorted(ans, key=lambda x:x[0])
    return ans

Resizing Array

In [8]:
l=[1,3,4,2,6,7]
print(len(l))
l=l[1:4]  # 4 is exclusive not inclusive i.e end index is exclusive
print(l)
print(len(l))

6
[3, 4, 2]
3


Reverse words in a string : The string can have multiple spaces inbetween two words

In [9]:
str="   Hello      There   Hi  "
ans=""

l=str.split()
l.reverse()
for i in l:
    ans+=i
    ans+=" "

print(ans)

Hi There Hello 


2D Array Traversal

In [12]:
arr=[[1,2,3],[4,5,6],[7,8,9]]

print(arr[0])
print(arr[2])

[1, 2, 3]
[7, 8, 9]


insert in 2D Array

In [13]:
arr=[[1,2,3],[4,5,6],[7,8,9]]
arr.insert(2,[11,12,13])
print(arr)

[[1, 2, 3], [4, 5, 6], [11, 12, 13], [7, 8, 9]]


reverse a list after given position

In [15]:
l=[1,2,3,4,5,6,7,8,9]
n=3
l[(n+1):]=l[-1:-(len(l)-n):-1]  # l[:-(len(l)-n):-1]
print(l)

[1, 2, 3, 4, 9, 8, 7, 6, 5]


Intersection of two array

In [16]:
from collections import *
map=OrderedDict()

l1=[1,3,5,2,5,8,2]
l2=[5,2,8,2,9,6]
ans=[]

l1=sorted(l1)
l2=sorted(l2)

for i in l1:
    map[i]=map.get(i,0)+1

for i in l2:
    if i in map and map[i]>0:
        ans.append(i)
        map[i]-=1

print(ans)

[2, 2, 5, 8]


Get only distinct elements in map

In [17]:
from collections import *
map=OrderedDict()

l1=[1,3,5,2,5,8,2]
l2=[5,2,8,2,9,6]
ans=[]

l1=sorted(l1)
l2=sorted(l2)

for i in l1:
    map[i]=map.get(i,1)

'''for i in l2:
    if i in map and map[i]>0:
        ans.append(i)
        map[i]-=1'''

print(map)
#print(ans)

#======== Only distinct elements intersection ========

from collections import *
map=OrderedDict()

l1=[1,3,5,2,5,8,2]
l2=[5,2,8,2,9,6]
ans=[]

l1=sorted(l1)
l2=sorted(l2)

for i in l1:
    map[i]=map.get(i,1)

for i in l2:
    if i in map and map[i]!=0:       # here map[i]!=0
        ans.append(i)
        map[i]-=1

print(ans)

OrderedDict([(1, 1), (2, 1), (3, 1), (5, 1), (8, 1)])
[2, 5, 8]


Copying into a new Array

In [18]:
from array import array
l=array('I',[1,2,3,4,5,6])
l.append(11)
l.remove(3)
print(l)

l.reverse()
print(l)

# copying into a new array
new=array(l.typecode,[ele for ele in l])
print(new)

array('I', [1, 2, 4, 5, 6, 11])
array('I', [11, 6, 5, 4, 2, 1])
array('I', [11, 6, 5, 4, 2, 1])


Array Inparrut

In [ ]:
from array import array
l=array('I',[])

n=int(input())

for i in range(n):
    x=int(input(f'Enter the {i}th element'))
    l.append(x)

print(l)

ARRAY COPY: SHALLOW AND DEEP

In [19]:
from numpy import *

arr1=array([1,2,5])

# Shallow Copy

arr2=arr1.view()

print(id(arr1))
print(id(arr2))

arr1[1]=22
print(arr2)

4460202288
4460202672
[ 1 22  5]


In [20]:
from numpy import *

arr1=array([1,2,5])

# Deep Copy

arr2=arr1.copy()

print(id(arr1))
print(id(arr2))

arr1[1]=22
print(arr1)
print(arr2)

4450210320
4460203248
[ 1 22  5]
[1 2 5]


2D ARRAY Rows and Columns

In [21]:
#2D MATRIX no of rows and columns

l=[[1,2,3],[4,5,6],[7,8,9]]

rows=len(l)

col=len(l[0])

print(rows)
print(col)

3
3


SORTING IN 2D ARRAYS

In [22]:
arr=[[2,1],[0.5,3],[1,2]]
arr.sort()  # Sorts on the basis of first element in 2D arrays

print(arr)

[[0.5, 3], [1, 2], [2, 1]]


2D Array Input

In [ ]:
# Taking input for 2D array
# 3 2
# 1 2
# 3 4
# 5 6

a=input().split()
row=int(a[0])
col=int(a[1])
arr=[]

for i in range(row):
    r=[int(j) for j in input().split()]
    arr.append(r)

print(arr)

Ninja and Crazy sum CODESTUDIO

In [25]:
l=[[1,2,3],[4,5,6],[7,8,9]]

ans=[[] for i in range(len(l))]  #2D Array empty initialization

for i in range(len(l)):
    for j in range(len(l[0])):
        sum=0                  
        for x in l[i][j+1:]:     # j+1 is out of bound for last element still it works and thus does nothing to sum and 0 is appended
            sum+=x
        ans[i].append(sum)

print(ans)

#=================OPTIMISED n*n approach=========>

l=[[1,2,3],[4,5,6],[7,8,9]]

n = len(l)
m = len(l[0])

for i in range(n):
    sum = 0
    for j in range(m-1 , -1, -1):
        temp = l[i][j]    # Storing array value in a temp variable
        l[i][j] = sum
        sum += temp

print(l)

[[5, 3, 0], [11, 6, 0], [17, 9, 0]]
[[5, 3, 0], [11, 6, 0], [17, 9, 0]]


Bubble Sort

In [28]:
# Bubble sort

# after each iteration one largest element will go to it's final position
# for eg in l=[10,5,9,4,2]
# after first iteration 10 will be at it's original pos output of first iteration : [5,9,4,2,10]
# second iteration [5,4,2,9,10]
# third iteration [4,2,5,9,10]

l=[10,5,9,4,2]
n=len(l)
for i in range(n-1):
    for j in range(n-1):
        if l[j]>l[j+1]:
            temp=l[j]
            l[j]=l[j+1]
            l[j+1]=temp
    print(l)

[5, 9, 4, 2, 10]
[5, 4, 2, 9, 10]
[4, 2, 5, 9, 10]
[2, 4, 5, 9, 10]


Selection Sort

In [38]:
# Selection sort

# find smallest element in array and fix it to starting position 
# then in second iteration leave first index and find min element in subsequent array and fix it to second index

# NOT NECESSARY YOU DO FROM REVERE ORDER CAN BE DONE FROM START TOO
# from reverse own method  (lil bit complex)

'''l=[10,5,9,4,2]
n=len(l)
for i in range(n):
    minm=l[-1]
    ind=-1
    for j in range(-1,-n+i-1,-1):
        if(l[j]<minm):
            ind=j
            minm=l[j]

    l[ind]=l[i]
    l[i]=minm
    print(l)
'''

l=[10,5,9,4,2]
n=len(l)
for i in range(n-1):   # n-2 is wrong no less that this iteration
    min_idx=i
    for j in range(i+1,n):
        if(l[j]<l[min_idx]):
            min_idx=j

    l[i],l[min_idx]=l[min_idx],l[i]
            
    print(l)



[2, 5, 9, 4, 10]
[2, 4, 9, 5, 10]
[2, 4, 5, 9, 10]
[2, 4, 5, 9, 10]


Insertion Sort

In [41]:
# Algorithm
'''To sort an array of size N in ascending order iterate over the array and compare the current element (key) to its predecessor
if the key element is smaller than its predecessor, compare it to the elements before. 
Move the greater elements one position up to make space for the swapped element.'''

l=[10,5,9,4,6]
n=len(l)
for i in range(n-1):
    k=i+1
    while(l[k]<l[k-1] and k>=1):
        l[k],l[k-1]=l[k-1],l[k]
        k-=1
    print(l)

[5, 10, 9, 4, 6]
[5, 9, 10, 4, 6]
[4, 5, 9, 10, 6]
[4, 5, 6, 9, 10]


Find Dup codestudio

In [43]:
l=[1,3,2,2,4]
map=[False for i in l]

def finddup(l):
    for i in l:
        if map[i-1]:
            return i
        else:
            map[i-1]=True

finddup(l)

2